export const sitemappages: string[] = [
    'about',
    'ai-painting',
    'chinese-color-picker',
    'drawfree',
    'excalidraw',
    'exchangerates',
    'global-weather',
    'json-editor',
    'qrcode-generator',
    'temperature-converter',
    'text-diff',
    'tui-editor',
    'webvm',
    'weight-converter',
  ];